---
apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkgs-kubeapps-cluster
  namespace: hphil
spec:
  distribution:
    version: v1.20
  topology:
    controlPlane:
      count: 1
      class: best-effort-medium
      storageClass: wcppolicy
    workers:
      count: 2
      class: best-effort-medium
      storageClass: wcppolicy
